load("//bazel:api_build_system.bzl", "api_proto_library_internal")

licenses(["notice"])  # Apache 2

api_proto_library_internal(
    name = "ip_allow_deny",
    srcs = ["ip_allow_deny.proto"],
    deps = ["//envoy/api/v2/core:address"],
)
