load("//bazel:api_build_system.bzl", "api_proto_library_internal")

licenses(["notice"])  # Apache 2

api_proto_library_internal(
    name = "ip",
    srcs = ["ip.proto"],
    deps = ["//envoy/api/v2/core:address"],
)
