load("//bazel:api_build_system.bzl", "api_proto_library_internal")

licenses(["notice"])  # Apache 2

api_proto_library_internal(
    name = "health_check_simple",
    srcs = ["health_check_simple.proto"],
)
